[package]
name = "initialization"
version = "0.1.0"
edition = "2024"

[dependencies]
type_pool = { path = "../type_pool" }
interpreter = { path = "../interpreter" }
runtime = { path = "../runtime" }
gc = { path = "../gc" }
scheduler = { path = "../scheduler" }
stack_pool = { path = "../stack_pool" }
nsbc = { path = "../nsbc" }
